version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5151:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nestjs
  test-db:
    image: postgres:13
    ports:
      - 5111:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - nestjs
networks:
  nestjs:
